### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by tmeftah** [tmeftah/Aora#32]

**Comment by tmeftah** [comment]
@NikhilRaikar17   The documentation issue will be an issue that we will not close at all. It will be all the time on progress.
we will create only one branch for it. each time oen of us want to add some hing to the documentaion branch, he pull write what every he have to write and then push.  every time we checkout this branch we have to pull the last develop into it. 
Pull request will be done when every we want? Let me know if you have also an idea hoe to do it in another way.

**Comment by NikhilRaikar17** [comment]
If we have a seperate documentation branch, this branch has to be constantly updated with new changes in develop else we will have merge conflicts and to resolve them would be a waste of time as this branch does not serve any purpose. 

Instead, why dont we follow the same process for the documentation aswell but without reviews. 

1. Create approrpiate issue for the documentation "as and when needed".
2. Merge this branch once the documentation is done
3. No need to request for any reviews from either of us
4. We keep the steps clear and concise by not changing anything.
5. If its a very small change in documentation, just add a commit directly into the develop but address the commit message with 
   "Docu-Update:<commit-msg>" (no need to create an issue and a branch for small documentation updates)

What would you think about this?

**Comment by tmeftah** [comment]
no because the branch feature-32/documentation will only update ReadMe file (or new *.md files), it will be no conflict when we merge it.
the point is that when you work on documentation branch, you have first to pull the develop, so that it will be each time on the same last level as develop when you start to add documentations.
